### ISSUE TITLE
Python 3 urllib

### ISSUE THREAD

**Issue by cyrilcros** [endrebak/godb#1]
Hi, calling `godb.get_annotations()` returns `AttributeError: module 'urllib' has no attribute 'urlretrieve'`.
This is a change introduced in Python 3, where you should use the urllib.request module. 

Could you also precise which Python version this is for? I am guessing Python 2.
Thanks!

**Comment by endrebak** [comment]
Thanks for reporting this. Should work for both 2 and 3 (like everything I write), so I am starting to look into it.

**Comment by endrebak** [comment]
```
try:
    from urllib import urlretrieve
except ImportError:
    from urllib.request import urlretrieve
```

Fixed it, thanks for taking the time to help me improve the library! (I did not run into this issue since the data was cached after testing with 2.7 first).

Please reopen if you encounter any issues.

```bash
pip install godb==0.0.5 --no-cache-dir
```
